### PR TITLE
Add registration/signup method

### PR DESCRIPTION
**Pull request by filipwojnicki**
Registration method with parameters: username, password, name, email. Returning true or false

### CODE REVIEW

**Comment by yatsenkolesh** [comment]
Hello. Talk me about use cases of automatically registration, please.

**Comment by filipwojnicki** [comment]
This method can be a simplification of the registration process. Many people needs to have multiaccounts for example bussiness, personal, etc. Instagram allows to have multi accounts.

**Comment by yatsenkolesh** [comment]
Okey. Thank you.

**Comment by filipwojnicki** [comment]
If u want i can add support for proxy for this project

**Comment by yatsenkolesh** [comment]
Yeap, all features will be a really great.

**Pull request merged**
